### ISSUE TITLE
Question about TnT dataset evaluation

### ISSUE THREAD

**Issue by countywest** [Open3DVLab/NeuRodin#4]
Hello, Thanks for sharing your great work.
I have a question about the evaluation for Tanks and Temples dataset.

TnT evaluation toolbox is based on comparing two point clouds (reconstruction and ground truth).
So the reconstructed mesh should be converted to a point cloud for the evaluation, but I cannot find the details on the paper.
Could you share the strategy you used for converting mesh to a point cloud for the TnT evaluation?
(ex: number of sampling points, sampling method, using filtering or not, etc..)
I'm also curious to know either evaluation metrics are sensitive to the sampling strategy or not, and uniform sampling on the surface mesh is just enough.

**Comment by yyfz** [comment]
Hi, thank you for your interest in our work!

Regarding the TNT training set, as outlined in our paper, we utilize the evaluation script available at [this link](https://github.com/isl-org/TanksAndTemples/blob/master/python_toolbox/evaluation/README.md). There are no parameters to adjust, and we directly provide our mesh generated from marching cubes (a .ply file with a resolution of 2048). The point sampling strategy is implemented using the official script.

For TNT Advanced, we submit our marching cubes-generated mesh (a .ply file with 2048 resolution) directly to [this platform](https://www.tanksandtemples.org/).

While it is true that a dense mesh may impact performance, we can selectively sample points in high-certainty areas. However, for a fair comparison, we haven't do that.

**Comment by countywest** [comment]
@yyfz 
Thank you for fast reply and clear illustration!

Actually, I have read the evaluation script before, and it loads the reconstructed geometry with ```o3d.io.read_point_cloud```, so I thought that the point sampling process is needed. However, as you said, it can be applied to a triangle mesh ply file. I found that it makes a pointcloud with the vertices of the triangle mesh (vertices of the mesh loaded from ```o3d.io.read_triangle_mesh``` and the pointcloud loaded from ```o3d.io.read_point_cloud``` are same).

Thanks for clarifying!
